steps:

# Pull latest Docker image for caching

# - name: 'gcr.io/cloud-builders/docker'
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     docker pull us.gcr.io/$PROJECT_ID/$_ENV_NAME:latest || exit 0

# Build image with tag 'latest' and pass decrypted Rails DB password, secret key as arguments
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '--tag', 'gcr.io/givees-295311/givees:givees-dev-1.1',
            '.'
        ]

# Push new image to Google Container Registry       
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/givees-295311/givees:givees-dev-1.1']

# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'givees', '--image', 'gcr.io/givees-295311/givees:givees-dev-1.1', '--region', 'us-central1','--platform', 'managed', '--allow-unauthenticated', '--set-cloudsql-instances', '$_CLOUD_SQL_INSTANCE']
