exports.adminPermission = {
  canSeeActivities: true,
  canChatToMerchant: false,
  canBlockCampion: false,
  canSeeCampion: true,
  canCreateProduct: true,
  canCreateCampion: true,
  canUpdateOwnAccount: true,
  canDeleteOwnAccount: false,
  canReadOwnAccount: true,
  canDeleteUser: false,
  canUpdateUser: false,
  canDeleteMerchant: false,
  canBlockMerchant: false,
  canUpdateMerchant: false,
  canReadMerchant: true,
  canCreateMerchant: false,
  canBlockAdmin: false,
  canUpdateAdmin: false,
  canDeleteAdmin: false,
  canReadAdmin: false,
  canCreateAdmin: false,
  canCreateUser: false,
  canBlockUser: false,
  canReadUser: true,
  canReadProduct: true,
  canEditProduct: false,
  canDeleteProduct: false,
  canReadCategory: true,
  canEditCategory: false,
  canDeleteCategory: false,
  canReadPromoCode: true,
  canCreatePromoCode: false,
  canEditPromoCode: false,
  canDeletePromoCode: false,
  //
  canBlockPromoCode: false,
  canBlockCategory: false,
  canBlockProduct: false,
  canReadVoucherHistory: false,
  canEditVoucherHistory: false,
  canBlockVoucherHistory: false,
  canDeleteVoucherHistory: false,
  canCreateVoucherHistory: false,

  //
  canReadSubCategory: false,
  canEditSubCategory: false,
  canBlockSubCategory: false,
  canDeleteSubCategory: false,
  canCreateSubCategory: false,
  //
  canReadPaymentDetail: false,
  canEditPaymentDetail: false,
  canBlockPaymentDetail: false,
  canDeletePaymentDetail: false,
  canCreatePaymentDetail: false,
  //
  canEditCampion: false,
  //
  canReadTransactionDetail: false,
  canEditTransactionDetail: false,
  canBlockTransactionDetail: false,
  canDeleteTransactionDetail: false,
  canCreateTransactionDetail: false,
  //
  canReadSupport: true,
  canEditSupport: false,
  canBlockSupport: false,
  canDeleteSupport: false,
  canCreateSupport: false,
  //
  canReadTermsCondition: false,
  canEditTermsCondition: false,
  canBlockTermsCondition: false,
  canDeleteTermsCondition: false,
  canCreateTermsCondition: false,
  //
  canReadActivityLog: false,
  canEditActivityLog: false,
  canBlockActivityLog: false,
  canDeleteActivityLog: false,
  canCreateActivityLog: false,
  //
  canReadAboutUs: false,
  canEditAboutUs: false,
  canBlockAboutUs: false,
  canDeleteAboutUs: false,
  canCreateAboutUs: false,
  //
  canReadContactUs: false,
  canEditContactUs: false,
  canBlockContactUs: false,
  canDeleteContactUs: false,
  canCreateContactUs: false,
  //
  canReadActionRadius: false,
  canEditActionRadius: false,
  canBlockActionRadius: false,
  canDeleteActionRadius: false,
  canCreateActionRadius: false,

  //
  canReadFaqs: false,
  canEditFaqs: false,
  canBlockFaqs: false,
  canDeleteFaqs: false,
  canCreateFaqs: false,

  //
  canReadSalesTax: false,
  canEditSalesTax: false,
  canBlockSalesTax: false,
  canDeleteSalesTax: false,
  canCreateSalesTax: false,
  //
  canReadPercentRate: false,
  canEditPercentRate: false,
  canBlockPercentRate: false,
  canDeletePercentRate: false,
  canCreatePercentRate: false,
  // /
  canReadAdditionalFees: false,
  canEditAdditionalFees: false,
  canBlockAdditionalFees: false,
  canDeleteAdditionalFees: false,
  canCreateAdditionalFees: false,
  // /

  canReadAppBanners: false,
  canEditAppBanners: false,
  canBlockAppBanners: false,
  canDeleteAppBanners: false,
  canCreateAppBanners: false,
  // /

  canReadHowToUse: false,
  canEditHowToUse: false,
  canBlockHowToUse: false,
  canDeleteHowToUse: false,
  canCreateHowToUse: false,
  canCreateCategory: false,
  canDeleteCampion: false,
  // /
  canReadRedemptions: false,
  canUpdateRedemptions: false,
  canDeleteRedemptions: false,
  //
  canReadSale: false,
  canUpdateSale: false,
  canDeleteSale: false,
  //
  canCreateCounter: false,
  canReadCounter: false,
  canUpdateCounter: false,
  //
  canCreatePrivacyPolicy: false,
  canReadPrivacyPolicy: true,
  canUpdatePrivacyPolicy: false,
  canDeletePrivacyPolicy: false,
  //
  canCreateContactService: true,
  canDeleteContactService: true,
  canEditContactService: true,
  canReadContactService: true,
};

exports.superAdminPermission = {
  canSeeActivities: true,
  canChatToMerchant: true,
  canBlockCampion: true,
  canSeeCampion: true,
  canCreateProduct: true,
  canCreateCampion: true,
  canUpdateOwnAccount: true,
  canDeleteOwnAccount: true,
  canReadOwnAccount: true,
  canDeleteUser: true,
  canUpdateUser: true,
  canDeleteMerchant: true,
  canBlockMerchant: true,
  canUpdateMerchant: true,
  canReadMerchant: true,
  canCreateMerchant: true,
  canBlockAdmin: true,
  canUpdateAdmin: true,
  canDeleteAdmin: true,
  canReadAdmin: true,
  canCreateAdmin: true,
  canCreateUser: true,
  canBlockUser: true,
  canReadUser: true,
  canReadProduct: true,
  canEditProduct: true,
  canDeleteProduct: true,
  canReadCategory: true,
  canEditCategory: true,
  canDeleteCategory: true,
  canReadPromoCode: true,

  canCreatePromoCode: true,
  canEditPromoCode: true,
  canDeletePromoCode: true,
  canBlockPromoCode: true,
  canBlockCategory: true,
  canBlockProduct: true,
  canReadVoucherHistory: true,
  canEditVoucherHistory: true,
  canBlockVoucherHistory: true,
  canDeleteVoucherHistory: true,
  canCreateVoucherHistory: true,
  canCreateCategory: true,
  canDeleteCampion: true,
  //
  canReadSubCategory: true,
  canEditSubCategory: true,
  canBlockSubCategory: true,
  canDeleteSubCategory: true,
  canCreateSubCategory: true,
  //
  canReadPaymentDetail: true,
  canEditPaymentDetail: true,
  canBlockPaymentDetail: true,
  canDeletePaymentDetail: true,
  canCreatePaymentDetail: true,

  //
  canEditCampion: true,
  //
  canReadTransactionDetail: true,
  canEditTransactionDetail: true,
  canBlockTransactionDetail: true,
  canDeleteTransactionDetail: true,
  canCreateTransactionDetail: true,

  //
  canReadSupport: true,
  canEditSupport: true,
  canBlockSupport: true,
  canDeleteSupport: true,
  canCreateSupport: true,

  //
  canReadTermsCondition: true,
  canEditTermsCondition: true,
  canBlockTermsCondition: true,
  canDeleteTermsCondition: true,
  canCreateTermsCondition: true,

  //
  canReadActivityLog: true,
  canEditActivityLog: true,
  canBlockActivityLog: true,
  canDeleteActivityLog: true,
  canCreateActivityLog: true,
  //
  canReadAboutUs: true,
  canEditAboutUs: true,
  canBlockAboutUs: true,
  canDeleteAboutUs: true,
  canCreateAboutUs: true,
  //
  canReadContactUs: true,
  canEditContactUs: true,
  canBlockContactUs: true,
  canDeleteContactUs: true,
  canCreateContactUs: true,
  //
  canReadActionRadius: true,
  canEditActionRadius: true,
  canBlockActionRadius: true,
  canDeleteActionRadius: true,
  canCreateActionRadius: true,

  //
  canReadFaqs: true,
  canEditFaqs: true,
  canBlockFaqs: true,
  canDeleteFaqs: true,
  canCreateFaqs: true,

  //
  canReadSalesTax: true,
  canEditSalesTax: true,
  canBlockSalesTax: true,
  canDeleteSalesTax: true,
  canCreateSalesTax: true,
  //
  canReadPercentRate: true,
  canEditPercentRate: true,
  canBlockPercentRate: true,
  canDeletePercentRate: true,
  canCreatePercentRate: true,
  // /
  canReadAdditionalFees: true,
  canEditAdditionalFees: true,
  canBlockAdditionalFees: true,
  canDeleteAdditionalFees: true,
  canCreateAdditionalFees: true,
  // /

  canReadAppBanners: true,
  canEditAppBanners: true,
  canBlockAppBanners: true,
  canDeleteAppBanners: true,
  canCreateAppBanners: true,
  // /

  canReadHowToUse: true,
  canEditHowToUse: true,
  canBlockHowToUse: true,
  canDeleteHowToUse: true,
  canCreateHowToUse: true,
  //
  canReadRedemptions: true,
  canUpdateRedemptions: true,
  canDeleteRedemptions: true,
  //
  canReadSale: true,
  canUpdateSale: true,
  canDeleteSale: true,
  //
  canCreateCounter: true,
  canReadCounter: true,
  canUpdateCounter: true,
  //
  canCreatePrivacyPolicy: true,
  canReadPrivacyPolicy: true,
  canUpdatePrivacyPolicy: true,
  canDeletePrivacyPolicy: true,
  //
  canCreateContactService: true,
  canDeleteContactService: true,
  canEditContactService: true,
  canReadContactService: true,
};

exports.merchantPermission = {
  canSeeActivities: false,
  canChatToMerchant: false,
  canBlockCampion: false,
  canSeeCampion: false,
  canCreateProduct: false,
  canCreateCampion: false,
  canUpdateOwnAccount: true,
  canDeleteOwnAccount: false,
  canReadOwnAccount: true,
  canDeleteUser: false,
  canUpdateUser: false,
  canDeleteMerchant: false,
  canBlockMerchant: false,
  canUpdateMerchant: false,
  canReadMerchant: false,
  canCreateMerchant: false,
  canBlockAdmin: false,
  canUpdateAdmin: false,
  canDeleteAdmin: false,
  canReadAdmin: false,
  canCreateAdmin: false,
  canCreateUser: false,
  canBlockUser: false,
  canReadUser: false,
  canReadProduct: false,
  canEditProduct: false,
  canDeleteProduct: false,
  canReadCategory: false,
  canEditCategory: false,
  canReadPromoCode: false,

  canCreatePromoCode: false,
  canEditPromoCode: false,
  canDeletePromoCode: false,
  canDeleteCategory: false,
  canBlockPromoCode: false,
  canBlockCategory: false,
  canBlockProduct: false,
  canReadVoucherHistory: false,
  canEditVoucherHistory: false,
  canBlockVoucherHistory: false,
  canDeleteVoucherHistory: false,
  canCreateVoucherHistory: false,
  canCreateCategory: false,
  canDeleteCampion: false,
  //
  canReadSubCategory: false,
  canEditSubCategory: false,
  canBlockSubCategory: false,
  canDeleteSubCategory: false,
  canCreateSubCategory: false,
  //
  canReadPaymentDetail: false,
  canEditPaymentDetail: false,
  canBlockPaymentDetail: false,
  canDeletePaymentDetail: false,
  canCreatePaymentDetail: false,

  //
  canEditCampion: false,
  //
  canReadTransactionDetail: false,
  canEditTransactionDetail: false,
  canBlockTransactionDetail: false,
  canDeleteTransactionDetail: false,
  canCreateTransactionDetail: false,

  //
  canReadSupport: true,
  canEditSupport: false,
  canBlockSupport: false,
  canDeleteSupport: false,
  canCreateSupport: false,

  //
  canReadTermsCondition: false,
  canEditTermsCondition: false,
  canBlockTermsCondition: false,
  canDeleteTermsCondition: false,
  canCreateTermsCondition: false,

  //
  canReadActivityLog: false,
  canEditActivityLog: false,
  canBlockActivityLog: false,
  canDeleteActivityLog: false,
  canCreateActivityLog: false,
  //
  canReadAboutUs: false,
  canEditAboutUs: false,
  canBlockAboutUs: false,
  canDeleteAboutUs: false,
  canCreateAboutUs: false,
  //
  canReadContactUs: false,
  canEditContactUs: false,
  canBlockContactUs: false,
  canDeleteContactUs: false,
  canCreateContactUs: false,
  //
  canReadActionRadius: false,
  canEditActionRadius: false,
  canBlockActionRadius: false,
  canDeleteActionRadius: false,
  canCreateActionRadius: false,

  //
  canReadFaqs: false,
  canEditFaqs: false,
  canBlockFaqs: false,
  canDeleteFaqs: false,
  canCreateFaqs: false,

  //
  canReadSalesTax: false,
  canEditSalesTax: false,
  canBlockSalesTax: false,
  canDeleteSalesTax: false,
  canCreateSalesTax: false,
  //
  canReadPercentRate: false,
  canEditPercentRate: false,
  canBlockPercentRate: false,
  canDeletePercentRate: false,
  canCreatePercentRate: false,
  // /
  canReadAdditionalFees: false,
  canEditAdditionalFees: false,
  canBlockAdditionalFees: false,
  canDeleteAdditionalFees: false,
  canCreateAdditionalFees: false,
  // /

  canReadAppBanners: false,
  canEditAppBanners: false,
  canBlockAppBanners: false,
  canDeleteAppBanners: false,
  canCreateAppBanners: false,
  // /

  canReadHowToUse: false,
  canEditHowToUse: false,
  canBlockHowToUse: false,
  canDeleteHowToUse: false,
  canCreateHowToUse: false,
  canReadRedemptions: false,
  canUpdateRedemptions: false,
  canDeleteRedemptions: false,
  //
  canReadSale: true,
  canUpdateSale: false,
  canDeleteSale: false,
  //
  canCreateCounter: false,
  canReadCounter: false,
  canUpdateCounter: false,
  //
  canCreatePrivacyPolicy: false,
  canReadPrivacyPolicy: false,
  canUpdatePrivacyPolicy: false,
  canDeletePrivacyPolicy: false,
  //
  canReadContactService: false,
};

exports.userPermission = {
  canCreateAdmin: false,
  canReadAdmin: false,
  canUpdateAdmin: false,
  canDeleteAdmin: false,
  canBlockMerchant: false,
  canCreateMerchant: false,
  canBlockAdmin: false,
  canReadMerchant: false,
  canUpdateMerchant: false,
  canDeleteMerchant: false,
  canCreateUser: false,
  canBlockUser: false,
  canReadUser: false,
  canUpdateUser: false,
  canDeleteUser: false,
  canReadOwnAccount: true,
  canDeleteOwnAccount: false,
  canUpdateOwnAccount: true,
  canCreateCampion: false,
  canCreateProduct: false,
  canSeeCampion: false,
  canBlockCampion: false,
  canChatToMerchant: false,
  canSeeActivities: false,
  canReadProduct: false,
  canEditProduct: false,
  canDeleteProduct: false,
  canReadCategory: false,
  canEditCategory: false,
  canDeleteCategory: false,
  canEditPromoCode: false,
  canReadPromoCode: false,
  canCreatePromoCode: false,
  canCreateCategory: false,
  canDeleteCampion: false,
  canDeletePromoCode: false,
  canBlockPromoCode: false,
  canBlockCategory: false,
  canBlockProduct: false,
  canReadVoucherHistory: false,
  canEditVoucherHistory: false,
  canBlockVoucherHistory: false,
  canDeleteVoucherHistory: false,
  canCreateVoucherHistory: false,

  //
  canReadSubCategory: false,
  canEditSubCategory: false,
  canBlockSubCategory: false,
  canDeleteSubCategory: false,
  canCreateSubCategory: false,
  //
  canReadPaymentDetail: false,
  canEditPaymentDetail: false,
  canBlockPaymentDetail: false,
  canDeletePaymentDetail: false,
  canCreatePaymentDetail: false,

  //
  canEditCampion: false,
  //
  canReadTransactionDetail: false,
  canEditTransactionDetail: false,
  canBlockTransactionDetail: false,
  canDeleteTransactionDetail: false,
  canCreateTransactionDetail: false,

  //
  canReadSupport: true,
  canEditSupport: false,
  canBlockSupport: false,
  canDeleteSupport: false,
  canCreateSupport: false,

  //
  canReadTermsCondition: true,
  canEditTermsCondition: false,
  canBlockTermsCondition: false,
  canDeleteTermsCondition: false,
  canCreateTermsCondition: false,

  //
  canReadActivityLog: false,
  canEditActivityLog: false,
  canBlockActivityLog: false,
  canDeleteActivityLog: false,
  canCreateActivityLog: false,
  //
  canReadAboutUs: false,
  canEditAboutUs: false,
  canBlockAboutUs: false,
  canDeleteAboutUs: false,
  canCreateAboutUs: false,
  //
  canReadContactUs: false,
  canEditContactUs: false,
  canBlockContactUs: false,
  canDeleteContactUs: false,
  canCreateContactUs: false,
  canCreateQuestion: true,
  //
  canReadActionRadius: false,
  canEditActionRadius: false,
  canBlockActionRadius: false,
  canDeleteActionRadius: false,
  canCreateActionRadius: false,

  //
  canReadFaqs: false,
  canEditFaqs: false,
  canBlockFaqs: false,
  canDeleteFaqs: false,
  canCreateFaqs: false,

  //
  canReadSalesTax: false,
  canEditSalesTax: false,
  canBlockSalesTax: false,
  canDeleteSalesTax: false,
  canCreateSalesTax: false,
  //
  canReadPercentRate: false,
  canEditPercentRate: false,
  canBlockPercentRate: false,
  canDeletePercentRate: false,
  canCreatePercentRate: false,
  // /
  canReadAdditionalFees: false,
  canEditAdditionalFees: false,
  canBlockAdditionalFees: false,
  canDeleteAdditionalFees: false,
  canCreateAdditionalFees: false,
  // /

  canReadAppBanners: false,
  canEditAppBanners: false,
  canBlockAppBanners: false,
  canDeleteAppBanners: false,
  canCreateAppBanners: false,
  // /

  canReadHowToUse: false,
  canEditHowToUse: false,
  canBlockHowToUse: false,
  canDeleteHowToUse: false,
  canCreateHowToUse: false,
  canReadRedemptions: false,
  canUpdateRedemptions: false,
  canDeleteRedemptions: false,
  //
  canReadSale: false,
  canUpdateSale: false,
  canDeleteSale: false,
  //
  canCreateCounter: false,
  canReadCounter: false,
  canUpdateCounter: false,
  //
  canCreatePrivacyPolicy: false,
  canReadPrivacyPolicy: false,
  canUpdatePrivacyPolicy: false,
  canDeletePrivacyPolicy: false,
  //
  canReadContactService: true,
};
